<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма регистрации</title>
    <link rel="stylesheet" href="static/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

</head>
<body>

<div class="container mt-4">
    <?php
    if (isset($_COOKIE['user']) == false) :
        ?>
        <div class="row">
            <div class="col">

                <form action="validation-form/check.php" method="post">
                    <h1>Регистрация</h1>
                    <input type="text" class="form-control" name="login" id="login" placeholder="Ваш логин"> <br>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Введите имя"> <br>
                    <input type="password" name="pass" id="pass" placeholder="Введите пароль"> <br>
                    <br>
                    <button class="btn btn-success" type="submit">Зарегестрироваться</button>

                </form>
            </div>
            <divl class="col">
                <form action="validation-form/auth.php" method="post">
                    <h1>Авторизация</h1>
                    <input type="text" class="form-control" name="login" id="login" placeholder="Ваш логин"> <br>
                    <input type="password" name="pass" id="pass" placeholder="Введите пароль"> <br>
                    <br>
                    <button class="btn btn-success" type="submit">Авторизироваться</button>

                </form>
            </divl>

        </div>
    <?php else:   ?>
    <p>Привет! <?= $_COOKIE['user'] ?>. Чтобы выйти нажмите здесь <a href="exit.php">здесь</a></p>
    <?php endif; ?>
</div>
</body>
</html>